# Generated by Django 5.0.1 on 2024-01-10 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activation_date',
        ),
    ]
