# Generated by Django 5.0.1 on 2024-01-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_user_activation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
